apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nginx.fullname" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "nginx.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: {{ .Values.ingress.ipBlock.cidr }}
      ports:
        - protocol: TCP
          port: {{ .Values.ingress.ipBlock.port }}
          endPort: {{ .Values.ingress.ipBlock.endPort }}
