apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nginx.fullname" . }}
spec:
  minAvailable: {{ .Values.PodDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "nginx.selectorLabels" . | nindent 6 }}
